import type { Ad, Brand } from "@/lib/types";

const brands: Brand[] = [
  { id: "brand-1", name: "Mitti Pantry", slug: "mitti-pantry", category: "Staples" },
  { id: "brand-2", name: "Nimboo Club", slug: "nimboo-club", category: "Beverages" },
  { id: "brand-3", name: "Good Grain Co.", slug: "good-grain", category: "Breakfast" },
  { id: "brand-4", name: "Coast & Kettle", slug: "coast-kettle", category: "Snacks" },
  { id: "brand-5", name: "The Chutney Room", slug: "chutney-room", category: "Condiments" },
  { id: "brand-6", name: "Sunday Cacao", slug: "sunday-cacao", category: "Sweets" },
];

const brand = (index: number) => brands[index];

export const demoAds: Ad[] = [
  {
    id: "demo-1",
    brand_id: brand(0).id,
    brand: brand(0),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "The everyday jar",
    cta: "Shop now",
    format: "Product demo",
    language: "English",
    category: "Staples",
    hook: "Ingredient-first",
    funnel_stage: "Consideration",
    creative_theme: "turmeric",
    status: "approved",
    first_seen_at: "2026-08-07",
    submitted_at: "2026-08-08",
    approved_at: "2026-08-09",
  },
  {
    id: "demo-2",
    brand_id: brand(1).id,
    brand: brand(1),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "A sharper kind of refreshment",
    cta: "Learn more",
    format: "Studio shot",
    language: "Hinglish",
    category: "Beverages",
    hook: "Sensory",
    funnel_stage: "Awareness",
    creative_theme: "lime",
    status: "approved",
    first_seen_at: "2026-08-03",
    submitted_at: "2026-08-04",
    approved_at: "2026-08-05",
  },
  {
    id: "demo-3",
    brand_id: brand(2).id,
    brand: brand(2),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "Breakfast, without the briefing",
    cta: "Shop now",
    format: "Offer-first",
    language: "English",
    category: "Breakfast",
    hook: "Convenience",
    funnel_stage: "Conversion",
    offer: "Sample offer",
    creative_theme: "oat",
    status: "approved",
    first_seen_at: "2026-07-29",
    submitted_at: "2026-07-30",
    approved_at: "2026-08-01",
  },
  {
    id: "demo-4",
    brand_id: brand(3).id,
    brand: brand(3),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "The crunch has a coastline",
    cta: "Shop now",
    format: "Lifestyle",
    language: "English",
    category: "Snacks",
    hook: "Origin story",
    funnel_stage: "Awareness",
    creative_theme: "sea",
    status: "approved",
    first_seen_at: "2026-07-23",
    submitted_at: "2026-07-24",
    approved_at: "2026-07-25",
  },
  {
    id: "demo-5",
    brand_id: brand(4).id,
    brand: brand(4),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "A spoonful changes the plate",
    cta: "View range",
    format: "How-to",
    language: "Hindi",
    category: "Condiments",
    hook: "Transformation",
    funnel_stage: "Consideration",
    creative_theme: "chilli",
    status: "approved",
    first_seen_at: "2026-07-18",
    submitted_at: "2026-07-19",
    approved_at: "2026-07-20",
  },
  {
    id: "demo-6",
    brand_id: brand(5).id,
    brand: brand(5),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "Cacao for the slow hour",
    cta: "Discover",
    format: "Founder-led",
    language: "English",
    category: "Sweets",
    hook: "Ritual",
    funnel_stage: "Awareness",
    creative_theme: "cacao",
    status: "approved",
    first_seen_at: "2026-07-13",
    submitted_at: "2026-07-14",
    approved_at: "2026-07-15",
  },
  {
    id: "pending-1",
    brand_id: brand(1).id,
    brand: brand(1),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "Three ingredients. One cold bottle.",
    cta: "Shop now",
    format: "Text overlay",
    language: "English",
    category: "Beverages",
    hook: "Ingredient-first",
    funnel_stage: "Consideration",
    creative_theme: "lime",
    status: "pending",
    first_seen_at: "2026-08-16",
    submitted_at: "2026-08-17",
  },
  {
    id: "pending-2",
    brand_id: brand(3).id,
    brand: brand(3),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "Office snack, sorted",
    cta: "Learn more",
    format: "UGC",
    language: "Hinglish",
    category: "Snacks",
    hook: "Problem / solution",
    funnel_stage: "Conversion",
    creative_theme: "sea",
    status: "pending",
    first_seen_at: "2026-08-15",
    submitted_at: "2026-08-16",
  },
  {
    id: "pending-3",
    brand_id: brand(4).id,
    brand: brand(4),
    platform: "meta",
    source_url: "https://www.facebook.com/ads/library/",
    headline: "Weeknight shortcut",
    cta: "View range",
    format: "Recipe",
    language: "Hindi",
    category: "Condiments",
    hook: "Convenience",
    funnel_stage: "Consideration",
    creative_theme: "chilli",
    status: "pending",
    first_seen_at: "2026-08-14",
    submitted_at: "2026-08-15",
  },
];

export const demoBrands = brands;
