export const BRANDS = [
  { name: "Amul", slug: "amul", category: "Dairy", query: "Amul", aliases: ["amul"] },
  { name: "Britannia", slug: "britannia", category: "Biscuits & Bakery", query: "Britannia Industries", aliases: ["britannia"] },
  { name: "Parle Products", slug: "parle-products", category: "Biscuits & Snacks", query: "Parle", aliases: ["parle", "parle g"] },
  { name: "Haldiram's", slug: "haldirams", category: "Snacks & Sweets", query: "Haldiram's", aliases: ["haldiram"] },
  { name: "Bikaji", slug: "bikaji", category: "Snacks & Sweets", query: "Bikaji Foods", aliases: ["bikaji"] },
  { name: "Paper Boat", slug: "paper-boat", category: "Beverages", query: "Paper Boat Drinks", aliases: ["paper boat"] },
  { name: "Epigamia", slug: "epigamia", category: "Dairy", query: "Epigamia", aliases: ["epigamia"] },
  { name: "The Whole Truth", slug: "the-whole-truth", category: "Healthy Snacks", query: "The Whole Truth Foods", aliases: ["whole truth"] },
  { name: "Yoga Bar", slug: "yoga-bar", category: "Healthy Snacks", query: "Yoga Bar India", aliases: ["yoga bar", "yogabar"] },
  { name: "Tata Soulfull", slug: "tata-soulfull", category: "Breakfast", query: "Tata Soulfull", aliases: ["tata soulfull", "soulfull"] },
  { name: "Slurrp Farm", slug: "slurrp-farm", category: "Kids Food", query: "Slurrp Farm", aliases: ["slurrp farm"] },
  { name: "Open Secret", slug: "open-secret", category: "Healthy Snacks", query: "Open Secret Snacks", aliases: ["open secret"] },
  { name: "Happilo", slug: "happilo", category: "Dry Fruits & Snacks", query: "Happilo", aliases: ["happilo"] },
  { name: "RiteBite Max Protein", slug: "ritebite-max-protein", category: "Protein Snacks", query: "RiteBite Max Protein", aliases: ["ritebite", "max protein"] },
  { name: "Too Yumm", slug: "too-yumm", category: "Snacks", query: "Too Yumm", aliases: ["too yumm", "tooyumm"] },
  { name: "Licious", slug: "licious", category: "Meat & Seafood", query: "Licious India", aliases: ["licious"] },
  { name: "Wingreens Farms", slug: "wingreens-farms", category: "Dips & Sauces", query: "Wingreens Farms", aliases: ["wingreens"] },
  { name: "Veeba", slug: "veeba", category: "Dips & Sauces", query: "Veeba Foods", aliases: ["veeba"] },
  { name: "Ching's Secret", slug: "chings-secret", category: "Instant Food", query: "Ching's Secret", aliases: ["ching s secret", "chings secret"] },
  { name: "MTR Foods", slug: "mtr-foods", category: "Packaged Food", query: "MTR Foods", aliases: ["mtr foods", "mtrfoods"] },
  { name: "iD Fresh Food", slug: "id-fresh-food", category: "Fresh & Ready-to-Cook", query: "iD Fresh Food", aliases: ["id fresh", "i d fresh"] },
  { name: "Saffola", slug: "saffola", category: "Breakfast & Staples", query: "Saffola", aliases: ["saffola"] },
  { name: "Cornitos", slug: "cornitos", category: "Snacks", query: "Cornitos", aliases: ["cornitos"] },
  { name: "Balaji Wafers", slug: "balaji-wafers", category: "Snacks", query: "Balaji Wafers", aliases: ["balaji wafers"] },
];
