// Curated Indian packaged-food and DTC brands. Restaurant chains and legacy staples
// are intentionally excluded so the library stays useful for consumer-brand research.
// Deployed catalogue revision: 2026-09-05.
export const BRANDS = [
  { name: "Amul", slug: "amul", category: "Dairy", query: "Amul", aliases: ["amul"] },
  { name: "Haldiram's", slug: "haldirams", category: "Snacks & Sweets", query: "Haldiram's", aliases: ["haldiram"] },
  { name: "Bikaji", slug: "bikaji", category: "Snacks & Sweets", query: "Bikaji Foods", aliases: ["bikaji"] },
  { name: "Paper Boat", slug: "paper-boat", category: "Beverages", query: "Paper Boat Drinks", aliases: ["paper boat"] },
  { name: "Epigamia", slug: "epigamia", category: "Dairy", query: "Epigamia", aliases: ["epigamia"] },
  { name: "The Whole Truth", slug: "the-whole-truth", category: "Healthy Snacks", query: "The Whole Truth Foods", aliases: ["whole truth"] },
  { name: "Yoga Bar", slug: "yoga-bar", category: "Healthy Snacks", query: "Yoga Bar India", aliases: ["yoga bar", "yogabar"] },
  { name: "Slurrp Farm", slug: "slurrp-farm", category: "Kids Food", query: "Slurrp Farm", aliases: ["slurrp farm"] },
  { name: "Open Secret", slug: "open-secret", category: "Healthy Snacks", query: "Open Secret Snacks", aliases: ["open secret"] },
  { name: "Happilo", slug: "happilo", category: "Dry Fruits & Snacks", query: "Happilo", aliases: ["happilo"] },
  { name: "RiteBite Max Protein", slug: "ritebite-max-protein", category: "Protein Snacks", query: "RiteBite Max Protein", aliases: ["ritebite", "max protein"] },
  { name: "Licious", slug: "licious", category: "Meat & Seafood", query: "Licious India", aliases: ["licious"] },
  { name: "Wingreens Farms", slug: "wingreens-farms", category: "Dips & Sauces", query: "Wingreens Farms", aliases: ["wingreens"] },
  { name: "Veeba", slug: "veeba", category: "Dips & Sauces", query: "Veeba Foods", aliases: ["veeba"] },
  { name: "Ching's Secret", slug: "chings-secret", category: "Instant Food", query: "Ching's Secret", aliases: ["ching s secret", "chings secret"] },
  { name: "MTR Foods", slug: "mtr-foods", category: "Packaged Food", query: "MTR Foods", aliases: ["mtr foods", "mtrfoods"] },
  { name: "iD Fresh Food", slug: "id-fresh-food", category: "Fresh & Ready-to-Cook", query: "iD Fresh Food", aliases: ["id fresh", "i d fresh"] },
  { name: "Cornitos", slug: "cornitos", category: "Snacks", query: "Cornitos", aliases: ["cornitos"] },
  { name: "Country Delight", slug: "country-delight", category: "Dairy", query: "Country Delight", aliases: ["country delight"] },
  { name: "Naturals Ice Cream", slug: "naturals-ice-cream", category: "Ice Cream", query: "Naturals Ice Cream", aliases: ["naturals ice cream", "naturals"] },
  { name: "Snackible", slug: "snackible", category: "Healthy Snacks", query: "Snackible", aliases: ["snackible"] },
  { name: "Nourish Organics", slug: "nourish-organics", category: "Healthy Snacks", query: "Nourish Organics", aliases: ["nourish organics"] },
  { name: "Eat Better", slug: "eat-better", category: "Healthy Snacks", query: "Eat Better Snacks", aliases: ["eat better"] },
  { name: "Raw Pressery", slug: "raw-pressery", category: "Beverages", query: "Raw Pressery", aliases: ["raw pressery"] },
  { name: "Lahori", slug: "lahori", category: "Beverages", query: "Lahori Drinks", aliases: ["lahori"] },
  { name: "FreshToHome", slug: "freshtohome", category: "Meat & Seafood", query: "FreshToHome", aliases: ["freshtohome", "fresh to home"] },
  { name: "Farmley", slug: "farmley", category: "Dry Fruits & Snacks", query: "Farmley", aliases: ["farmley"] },
  { name: "TagZ Foods", slug: "tagz-foods", category: "Healthy Snacks", query: "TagZ Foods", aliases: ["tagz", "tagz foods"] },
  { name: "4700BC Popcorn", slug: "4700bc-popcorn", category: "Snacks", query: "4700BC Popcorn", aliases: ["4700bc", "4700 bc"] },
  { name: "Anveshan", slug: "anveshan", category: "Staples", query: "Anveshan", aliases: ["anveshan"] },
  { name: "Aazol", slug: "aazol", category: "Regional Food", query: "Aazol", aliases: ["aazol"] },
  { name: "The Gourmet Jar", slug: "the-gourmet-jar", category: "Dips & Sauces", query: "The Gourmet Jar", aliases: ["gourmet jar"] },
  { name: "Sprig", slug: "sprig", category: "Ingredients", query: "Sprig Foods India", aliases: ["sprig"] },
  { name: "Bombay Sweet Shop", slug: "bombay-sweet-shop", category: "Snacks & Sweets", query: "Bombay Sweet Shop", aliases: ["bombay sweet shop"] },
  { name: "The Baker's Dozen", slug: "the-bakers-dozen", category: "Bakery", query: "The Baker's Dozen India", aliases: ["bakers dozen", "the baker s dozen"] },
  { name: "Blue Tokai Coffee", slug: "blue-tokai", category: "Coffee", query: "Blue Tokai Coffee", aliases: ["blue tokai"] },
  { name: "Sleepy Owl Coffee", slug: "sleepy-owl", category: "Coffee", query: "Sleepy Owl Coffee", aliases: ["sleepy owl"] },
  { name: "Rage Coffee", slug: "rage-coffee", category: "Coffee", query: "Rage Coffee", aliases: ["rage coffee"] },
  { name: "Country Bean", slug: "country-bean", category: "Coffee", query: "Country Bean Coffee", aliases: ["country bean"] },
  { name: "Bevzilla", slug: "bevzilla", category: "Beverages", query: "Bevzilla", aliases: ["bevzilla"] },
  { name: "Jimmy's Cocktails", slug: "jimmys-cocktails", category: "Beverages", query: "Jimmy's Cocktails", aliases: ["jimmys", "jimmy s cocktails"] },
  { name: "Svami", slug: "svami", category: "Beverages", query: "Svami Drinks", aliases: ["svami"] },
  { name: "Pluckk", slug: "pluckk", category: "Fresh Food", query: "Pluckk", aliases: ["pluckk"] },
  { name: "Akshayakalpa Organic", slug: "akshayakalpa-organic", category: "Dairy", query: "Akshayakalpa Organic", aliases: ["akshayakalpa"] },
  { name: "Wellbeing Nutrition", slug: "wellbeing-nutrition", category: "Nutrition", query: "Wellbeing Nutrition", aliases: ["wellbeing nutrition"] },
  { name: "Oziva", slug: "oziva", category: "Nutrition", query: "Oziva", aliases: ["oziva"] },
  { name: "The Health Factory", slug: "the-health-factory", category: "Bakery", query: "The Health Factory", aliases: ["health factory"] },
  { name: "Go Desi", slug: "go-desi", category: "Snacks", query: "Go Desi Snacks", aliases: ["go desi"] },
  { name: "Nourish You", slug: "nourish-you", category: "Healthy Snacks", query: "Nourish You", aliases: ["nourish you"] },
  { name: "Fit & Flex", slug: "fit-and-flex", category: "Healthy Snacks", query: "Fit & Flex", aliases: ["fit flex"] },
  { name: "Masala Tokri", slug: "masala-tokri", category: "Ingredients", query: "Masala Tokri", aliases: ["masala tokri"] },
  { name: "The Better Flour", slug: "the-better-flour", category: "Staples", query: "The Better Flour", aliases: ["better flour"] },
  { name: "Millet Amma", slug: "millet-amma", category: "Packaged Food", query: "Millet Amma", aliases: ["millet amma"] },
  { name: "Organic Tattva", slug: "organic-tattva", category: "Staples", query: "Organic Tattva", aliases: ["organic tattva"] },
  { name: "24 Mantra Organic", slug: "24-mantra-organic", category: "Staples", query: "24 Mantra Organic", aliases: ["24 mantra"] },
  { name: "Smoor Chocolates", slug: "smoor", category: "Snacks & Sweets", query: "Smoor Chocolates", aliases: ["smoor"] },
  { name: "Mason & Co", slug: "mason-and-co", category: "Snacks & Sweets", query: "Mason & Co Chocolate", aliases: ["mason co"] },
  { name: "Paul and Mike", slug: "paul-and-mike", category: "Snacks & Sweets", query: "Paul and Mike Chocolate", aliases: ["paul mike"] },
  { name: "Manam Chocolate", slug: "manam-chocolate", category: "Snacks & Sweets", query: "Manam Chocolate", aliases: ["manam"] },
  { name: "Araku Coffee", slug: "araku-coffee", category: "Coffee", query: "Araku Coffee", aliases: ["araku"] },
  { name: "Third Wave Coffee", slug: "third-wave-coffee", category: "Coffee", query: "Third Wave Coffee", aliases: ["third wave coffee"] },
  { name: "Beanly Coffee", slug: "beanly-coffee", category: "Coffee", query: "Beanly Coffee", aliases: ["beanly"] },
  { name: "Goodmylk", slug: "goodmylk", category: "Dairy", query: "Goodmylk", aliases: ["goodmylk"] },
  { name: "Alt Co", slug: "alt-co", category: "Dairy", query: "Alt Co India", aliases: ["alt co"] },
  { name: "Grabenord", slug: "grabenord", category: "Dairy", query: "Grabenord", aliases: ["grabenord"] },
  { name: "Let's Try", slug: "lets-try", category: "Snacks", query: "Let's Try Snacks", aliases: ["lets try"] },
  { name: "Britannia", slug: "britannia", category: "Packaged Food", query: "Britannia Industries", aliases: ["britannia"] },
  { name: "Parle Products", slug: "parle-products", category: "Packaged Food", query: "Parle Products", aliases: ["parle products", "parle g"] },
  { name: "MAGGI", slug: "maggi", category: "Instant Food", query: "MAGGI India", aliases: ["maggi"] },
  { name: "Sunfeast", slug: "sunfeast", category: "Packaged Food", query: "Sunfeast", aliases: ["sunfeast"] },
  { name: "Bingo!", slug: "bingo", category: "Snacks", query: "Bingo Snacks India", aliases: ["bingo snacks", "bingo"] },
  { name: "Tata Sampann", slug: "tata-sampann", category: "Staples", query: "Tata Sampann", aliases: ["tata sampann"] },
  { name: "Tata Soulfull", slug: "tata-soulfull", category: "Healthy Snacks", query: "Tata Soulfull", aliases: ["tata soulfull", "soulfull"] },
  { name: "Saffola", slug: "saffola", category: "Healthy Food", query: "Saffola", aliases: ["saffola"] },
  { name: "Lay's India", slug: "lays-india", category: "Snacks", query: "Lay's India", aliases: ["lay s india", "lays india", "lay s"] },
  { name: "Kurkure", slug: "kurkure", category: "Snacks", query: "Kurkure India", aliases: ["kurkure"] },
  { name: "Too Yumm!", slug: "too-yumm", category: "Healthy Snacks", query: "Too Yumm", aliases: ["too yumm"] },
  { name: "Beyond Snack", slug: "beyond-snack", category: "Snacks", query: "Beyond Snack", aliases: ["beyond snack"] },
  { name: "Cadbury Dairy Milk", slug: "cadbury-dairy-milk", category: "Snacks & Sweets", query: "Cadbury Dairy Milk India", aliases: ["cadbury dairy milk", "cadbury"] },
  { name: "Oreo India", slug: "oreo-india", category: "Packaged Food", query: "Oreo India", aliases: ["oreo india", "oreo"] },
  { name: "Coca-Cola India", slug: "coca-cola-india", category: "Beverages", query: "Coca-Cola India", aliases: ["coca cola india", "coca cola"] },
  { name: "Pepsi India", slug: "pepsi-india", category: "Beverages", query: "Pepsi India", aliases: ["pepsi india", "pepsi"] },
  { name: "Thums Up", slug: "thums-up", category: "Beverages", query: "Thums Up India", aliases: ["thums up"] },
  { name: "Maaza", slug: "maaza", category: "Beverages", query: "Maaza India", aliases: ["maaza"] },
  { name: "Real Fruit Power", slug: "real-fruit-power", category: "Beverages", query: "Real Fruit Power", aliases: ["real fruit power"] },
  { name: "Tropicana India", slug: "tropicana-india", category: "Beverages", query: "Tropicana India", aliases: ["tropicana india", "tropicana"] },
  { name: "Mother Dairy", slug: "mother-dairy", category: "Dairy", query: "Mother Dairy", aliases: ["mother dairy"] },
  { name: "Nandini Milk", slug: "nandini-milk", category: "Dairy", query: "Nandini Milk", aliases: ["nandini milk", "nandini"] },
  { name: "Heritage Foods", slug: "heritage-foods", category: "Dairy", query: "Heritage Foods", aliases: ["heritage foods"] },
  { name: "Milky Mist", slug: "milky-mist", category: "Dairy", query: "Milky Mist", aliases: ["milky mist"] },
  { name: "Kwality Wall's", slug: "kwality-walls", category: "Ice Cream", query: "Kwality Wall's India", aliases: ["kwality wall s", "kwality walls"] },
  { name: "Havmor Ice Creams", slug: "havmor", category: "Ice Cream", query: "Havmor Ice Creams", aliases: ["havmor ice creams", "havmor"] },
  { name: "McCain India", slug: "mccain-india", category: "Frozen Food", query: "McCain India", aliases: ["mccain india", "mccain"] },
  { name: "Prasuma", slug: "prasuma", category: "Frozen Food", query: "Prasuma", aliases: ["prasuma"] },
  { name: "Pintola", slug: "pintola", category: "Healthy Food", query: "Pintola", aliases: ["pintola"] },
  { name: "Alpino", slug: "alpino", category: "Healthy Food", query: "Alpino Foods", aliases: ["alpino foods", "alpino"] },
  { name: "MyFitness", slug: "myfitness", category: "Healthy Food", query: "MyFitness Peanut Butter", aliases: ["myfitness", "my fitness"] },
  { name: "True Elements", slug: "true-elements", category: "Healthy Snacks", query: "True Elements", aliases: ["true elements"] },
  { name: "Timios", slug: "timios", category: "Kids Food", query: "Timios", aliases: ["timios"] },
  { name: "Early Foods", slug: "early-foods", category: "Kids Food", query: "Early Foods", aliases: ["early foods"] },
  { name: "Kapiva", slug: "kapiva", category: "Nutrition", query: "Kapiva", aliases: ["kapiva"] },
  { name: "Plix", slug: "plix", category: "Nutrition", query: "Plix Life", aliases: ["plix life", "plix"] },
  { name: "Gits Food", slug: "gits-food", category: "Instant Food", query: "Gits Food", aliases: ["gits food", "gits"] },
  { name: "Aashirvaad", slug: "aashirvaad", category: "Staples", query: "Aashirvaad", aliases: ["aashirvaad"] },
  { name: "Fortune Foods", slug: "fortune-foods", category: "Staples", query: "Fortune Foods", aliases: ["fortune foods"] },
  { name: "Catch Foods", slug: "catch-foods", category: "Ingredients", query: "Catch Foods", aliases: ["catch foods", "catch spices"] },
  { name: "Everest Spices", slug: "everest-spices", category: "Ingredients", query: "Everest Spices", aliases: ["everest spices", "everest masala"] },
  { name: "MDH Spices", slug: "mdh-spices", category: "Ingredients", query: "MDH Spices", aliases: ["mdh spices", "mdh masala"] },
  { name: "Tata Tea", slug: "tata-tea", category: "Tea", query: "Tata Tea", aliases: ["tata tea"] },
  { name: "Brooke Bond Red Label", slug: "red-label-tea", category: "Tea", query: "Brooke Bond Red Label", aliases: ["brooke bond red label", "red label tea"] },
  { name: "Nescafé India", slug: "nescafe-india", category: "Coffee", query: "Nescafe India", aliases: ["nescafe india", "nescafe"] },
  { name: "BRU Coffee", slug: "bru-coffee", category: "Coffee", query: "BRU Coffee India", aliases: ["bru coffee"] },
  { name: "Sweet Karam Coffee", slug: "sweet-karam-coffee", category: "Coffee", query: "Sweet Karam Coffee", aliases: ["sweet karam coffee", "sweet karam koffee"] },
  { name: "VS Mani & Co", slug: "vs-mani", category: "Snacks", query: "VS Mani & Co", aliases: ["vs mani", "vs mani & co"] },
  { name: "Subko Coffee", slug: "subko-coffee", category: "Coffee", query: "Subko Coffee", aliases: ["subko", "subko coffee"] },
  { name: "MasterChow", slug: "masterchow", category: "Dips & Sauces", query: "MasterChow", aliases: ["masterchow", "master chow"] },
  { name: "NoCap Foods", slug: "nocap-foods", category: "Healthy Snacks", query: "NoCap Foods", aliases: ["nocap", "nocap foods"] },
  { name: "Two Brothers Organic Farms", slug: "two-brothers-organic-farms", category: "Staples", query: "Two Brothers Organic Farms", aliases: ["two brothers organic", "two brothers farms"] },
  { name: "Troo Good", slug: "troo-good", category: "Healthy Snacks", query: "Troo Good", aliases: ["troo good", "troogood"] },
  { name: "Yu", slug: "yu", category: "Packaged Food", query: "Yu Foodlabs", aliases: ["yu foodlabs", "yu foods"] },
  { name: "Sorrentina", slug: "sorrentina", category: "Packaged Food", query: "Sorrentina", aliases: ["sorrentina"] },
  { name: "Wakao Foods", slug: "wakao", category: "Plant-based Food", query: "Wakao Foods", aliases: ["wakao", "wakao foods"] },
  { name: "The Divine Foods", slug: "the-divine-foods", category: "Healthy Food", query: "The Divine Foods", aliases: ["divine foods"] },
  { name: "Storia Foods", slug: "storia", category: "Beverages", query: "Storia Foods", aliases: ["storia", "storia foods"] },
  { name: "VAHDAM India", slug: "vahdam-india", category: "Tea", query: "VAHDAM India", aliases: ["vahdam", "vahdam india"] },
  { name: "Tea Trunk", slug: "tea-trunk", category: "Tea", query: "Tea Trunk", aliases: ["tea trunk"] },
  { name: "TGL Co.", slug: "tgl-co", category: "Tea", query: "TGL Co", aliases: ["tgl co", "the good life company"] },
  { name: "Teabox", slug: "teabox", category: "Tea", query: "Teabox", aliases: ["teabox"] },
  { name: "SLAY Coffee", slug: "slay-coffee", category: "Coffee", query: "SLAY Coffee", aliases: ["slay coffee", "dropkaffe"] },
  { name: "The Flying Squirrel", slug: "the-flying-squirrel", category: "Coffee", query: "The Flying Squirrel Coffee", aliases: ["the flying squirrel", "flying squirrel coffee"] },
  { name: "Dope Coffee Roasters", slug: "dope-coffee", category: "Coffee", query: "Dope Coffee Roasters", aliases: ["dope coffee", "dope coffee roasters"] },
  { name: "Natureland Organics", slug: "natureland-organics", category: "Staples", query: "Natureland Organics", aliases: ["natureland", "natureland organics"] },
  { name: "Pascati", slug: "pascati", category: "Chocolate", query: "Pascati", aliases: ["pascati chocolate"] },
  { name: "La Folie", slug: "la-folie", category: "Chocolate", query: "La Folie Chocolate", aliases: ["la folie", "lafolie"] },
  { name: "Ether Atelier", slug: "ether-atelier", category: "Chocolate", query: "Ether Atelier", aliases: ["ether atelier", "ether chocolate"] },
  { name: "NOTO Ice Cream", slug: "noto-ice-cream", category: "Ice Cream", query: "NOTO Ice Cream", aliases: ["noto", "noto ice cream"] },
  { name: "Go Zero", slug: "go-zero", category: "Ice Cream", query: "Go Zero Ice Cream", aliases: ["go zero", "go zero ice cream"] },
  { name: "Bombucha", slug: "bombucha", category: "Beverages", query: "Bombucha", aliases: ["bombucha"] },
  { name: "Bhu Kombucha", slug: "bhu-kombucha", category: "Beverages", query: "Bhu Kombucha", aliases: ["bhu kombucha", "bhu"] },
  { name: "Zissto", slug: "zissto", category: "Dips & Sauces", query: "Zissto", aliases: ["zissto"] },
  { name: "Sirimiri", slug: "sirimiri", category: "Healthy Snacks", query: "Sirimiri Foods", aliases: ["sirimiri", "sirimiri foods"] },
  { name: "Snack Amor", slug: "snack-amor", category: "Snacks", query: "Snack Amor", aliases: ["snack amor"] },
  { name: "Mr. Makhana", slug: "mr-makhana", category: "Snacks", query: "Mr Makhana", aliases: ["mr makhana", "mr. makhana"] },
  { name: "The Healthy Binge", slug: "the-healthy-binge", category: "Healthy Snacks", query: "The Healthy Binge", aliases: ["healthy binge"] },
  { name: "LO Foods", slug: "lo-foods", category: "Healthy Food", query: "LO Foods", aliases: ["lo foods"] },
  { name: "SuperYou", slug: "superyou", category: "Healthy Snacks", query: "SuperYou", aliases: ["superyou", "super you"] },
  { name: "Milk Mantra", slug: "milk-mantra", category: "Dairy", query: "Milk Mantra", aliases: ["milk mantra"] },
  { name: "Sid's Farm", slug: "sids-farm", category: "Dairy", query: "Sid's Farm", aliases: ["sid s farm", "sids farm"] },
  { name: "Doodhvale Farms", slug: "doodhvale-farms", category: "Dairy", query: "Doodhvale Farms", aliases: ["doodhvale", "doodhvale farms"] },
  { name: "OneGood", slug: "onegood", category: "Plant-based Food", query: "OneGood", aliases: ["onegood", "one good"] },
  { name: "Aadvik Foods", slug: "aadvik", category: "Dairy", query: "Aadvik Foods", aliases: ["aadvik", "aadvik foods"] },
  { name: "Tulum Coffee", slug: "tulum-coffee", category: "Coffee", query: "Tulum Coffee", aliases: ["tulum coffee", "tulum"] },
  { name: "Tea Origin", slug: "tea-origin", category: "Tea", query: "Tea Origin", aliases: ["tea origin", "teaorigin"] },
  { name: "Goodwyn Tea", slug: "goodwyn-tea", category: "Tea", query: "Goodwyn Tea", aliases: ["goodwyn tea", "goodwyn"] },
  { name: "KC Roasters", slug: "kc-roasters", category: "Coffee", query: "KC Roasters", aliases: ["kc roasters", "kc roaster"] },
  { name: "Farmery", slug: "farmery", category: "Healthy Food", query: "Farmery", aliases: ["farmery"] },
  { name: "Nature's Box", slug: "natures-box", category: "Healthy Snacks", query: "Nature's Box", aliases: ["nature s box", "natures box"] },
  { name: "Ketofy", slug: "ketofy", category: "Healthy Snacks", query: "Ketofy", aliases: ["ketofy"] },
  { name: "Pyberry", slug: "pyberry", category: "Healthy Snacks", query: "Pyberry", aliases: ["pyberry"] },
  { name: "Eat Anytime", slug: "eat-anytime", category: "Healthy Snacks", query: "Eat Anytime", aliases: ["eat anytime"] },
  { name: "Cocotrail", slug: "cocotrail", category: "Snacks", query: "Cocotrail", aliases: ["cocotrail"] },
  { name: "Nutty Yogi", slug: "nutty-yogi", category: "Healthy Snacks", query: "Nutty Yogi", aliases: ["nutty yogi"] },
  { name: "Healthy Master", slug: "healthy-master", category: "Healthy Snacks", query: "Healthy Master", aliases: ["healthy master"] },
  { name: "WickedGüd", slug: "wicked-gud", category: "Frozen Food", query: "WickedGüd", aliases: ["wicked gud", "wickedgud"] },
  { name: "ZOFF", slug: "zoff", category: "Ingredients", query: "ZOFF", aliases: ["zoff"] },
  { name: "Naagin", slug: "naagin", category: "Dips & Sauces", query: "Naagin", aliases: ["naagin"] },
  { name: "Barosi", slug: "barosi", category: "Dairy", query: "Barosi", aliases: ["barosi"] },
  { name: "Blue Tea", slug: "blue-tea", category: "Tea", query: "Blue Tea", aliases: ["blue tea"] },
];
