// Curated Indian packaged-food and DTC brands. Restaurant chains and legacy staples
// are intentionally excluded so the library stays useful for consumer-brand research.
// Deployed catalogue revision: 2026-08-19.
export const BRANDS = [
  { name: "Amul", slug: "amul", category: "Dairy", query: "Amul", aliases: ["amul"] },
  { name: "Haldiram's", slug: "haldirams", category: "Snacks & Sweets", query: "Haldiram's", aliases: ["haldiram"] },
  { name: "Bikaji", slug: "bikaji", category: "Snacks & Sweets", query: "Bikaji Foods", aliases: ["bikaji"] },
  { name: "Paper Boat", slug: "paper-boat", category: "Beverages", query: "Paper Boat Drinks", aliases: ["paper boat"] },
  { name: "Epigamia", slug: "epigamia", category: "Dairy", query: "Epigamia", aliases: ["epigamia"] },
  { name: "The Whole Truth", slug: "the-whole-truth", category: "Healthy Snacks", query: "The Whole Truth Foods", aliases: ["whole truth"] },
  { name: "Yoga Bar", slug: "yoga-bar", category: "Healthy Snacks", query: "Yoga Bar India", aliases: ["yoga bar", "yogabar"] },
  { name: "Slurrp Farm", slug: "slurrp-farm", category: "Kids Food", query: "Slurrp Farm", aliases: ["slurrp farm"] },
  { name: "Open Secret", slug: "open-secret", category: "Healthy Snacks", query: "Open Secret Snacks", aliases: ["open secret"] },
  { name: "Happilo", slug: "happilo", category: "Dry Fruits & Snacks", query: "Happilo", aliases: ["happilo"] },
  { name: "RiteBite Max Protein", slug: "ritebite-max-protein", category: "Protein Snacks", query: "RiteBite Max Protein", aliases: ["ritebite", "max protein"] },
  { name: "Licious", slug: "licious", category: "Meat & Seafood", query: "Licious India", aliases: ["licious"] },
  { name: "Wingreens Farms", slug: "wingreens-farms", category: "Dips & Sauces", query: "Wingreens Farms", aliases: ["wingreens"] },
  { name: "Veeba", slug: "veeba", category: "Dips & Sauces", query: "Veeba Foods", aliases: ["veeba"] },
  { name: "Ching's Secret", slug: "chings-secret", category: "Instant Food", query: "Ching's Secret", aliases: ["ching s secret", "chings secret"] },
  { name: "MTR Foods", slug: "mtr-foods", category: "Packaged Food", query: "MTR Foods", aliases: ["mtr foods", "mtrfoods"] },
  { name: "iD Fresh Food", slug: "id-fresh-food", category: "Fresh & Ready-to-Cook", query: "iD Fresh Food", aliases: ["id fresh", "i d fresh"] },
  { name: "Cornitos", slug: "cornitos", category: "Snacks", query: "Cornitos", aliases: ["cornitos"] },
  { name: "Country Delight", slug: "country-delight", category: "Dairy", query: "Country Delight", aliases: ["country delight"] },
  { name: "Naturals Ice Cream", slug: "naturals-ice-cream", category: "Ice Cream", query: "Naturals Ice Cream", aliases: ["naturals ice cream", "naturals"] },
  { name: "Snackible", slug: "snackible", category: "Healthy Snacks", query: "Snackible", aliases: ["snackible"] },
  { name: "Nourish Organics", slug: "nourish-organics", category: "Healthy Snacks", query: "Nourish Organics", aliases: ["nourish organics"] },
  { name: "Eat Better", slug: "eat-better", category: "Healthy Snacks", query: "Eat Better Snacks", aliases: ["eat better"] },
  { name: "Raw Pressery", slug: "raw-pressery", category: "Beverages", query: "Raw Pressery", aliases: ["raw pressery"] },
  { name: "Lahori", slug: "lahori", category: "Beverages", query: "Lahori Drinks", aliases: ["lahori"] },
  { name: "FreshToHome", slug: "freshtohome", category: "Meat & Seafood", query: "FreshToHome", aliases: ["freshtohome", "fresh to home"] },
  { name: "Farmley", slug: "farmley", category: "Dry Fruits & Snacks", query: "Farmley", aliases: ["farmley"] },
  { name: "TagZ Foods", slug: "tagz-foods", category: "Healthy Snacks", query: "TagZ Foods", aliases: ["tagz", "tagz foods"] },
  { name: "4700BC Popcorn", slug: "4700bc-popcorn", category: "Snacks", query: "4700BC Popcorn", aliases: ["4700bc", "4700 bc"] },
  { name: "Anveshan", slug: "anveshan", category: "Staples", query: "Anveshan", aliases: ["anveshan"] },
  { name: "Aazol", slug: "aazol", category: "Regional Food", query: "Aazol", aliases: ["aazol"] },
  { name: "The Gourmet Jar", slug: "the-gourmet-jar", category: "Dips & Sauces", query: "The Gourmet Jar", aliases: ["gourmet jar"] },
  { name: "Sprig", slug: "sprig", category: "Ingredients", query: "Sprig Foods India", aliases: ["sprig"] },
  { name: "Bombay Sweet Shop", slug: "bombay-sweet-shop", category: "Snacks & Sweets", query: "Bombay Sweet Shop", aliases: ["bombay sweet shop"] },
  { name: "The Baker's Dozen", slug: "the-bakers-dozen", category: "Bakery", query: "The Baker's Dozen India", aliases: ["bakers dozen", "the baker s dozen"] },
  { name: "Blue Tokai Coffee", slug: "blue-tokai", category: "Coffee", query: "Blue Tokai Coffee", aliases: ["blue tokai"] },
  { name: "Sleepy Owl Coffee", slug: "sleepy-owl", category: "Coffee", query: "Sleepy Owl Coffee", aliases: ["sleepy owl"] },
  { name: "Rage Coffee", slug: "rage-coffee", category: "Coffee", query: "Rage Coffee", aliases: ["rage coffee"] },
  { name: "Country Bean", slug: "country-bean", category: "Coffee", query: "Country Bean Coffee", aliases: ["country bean"] },
  { name: "Bevzilla", slug: "bevzilla", category: "Beverages", query: "Bevzilla", aliases: ["bevzilla"] },
  { name: "Jimmy's Cocktails", slug: "jimmys-cocktails", category: "Beverages", query: "Jimmy's Cocktails", aliases: ["jimmys", "jimmy s cocktails"] },
  { name: "Svami", slug: "svami", category: "Beverages", query: "Svami Drinks", aliases: ["svami"] },
  { name: "Pluckk", slug: "pluckk", category: "Fresh Food", query: "Pluckk", aliases: ["pluckk"] },
  { name: "Akshayakalpa Organic", slug: "akshayakalpa-organic", category: "Dairy", query: "Akshayakalpa Organic", aliases: ["akshayakalpa"] },
  { name: "Wellbeing Nutrition", slug: "wellbeing-nutrition", category: "Nutrition", query: "Wellbeing Nutrition", aliases: ["wellbeing nutrition"] },
  { name: "Oziva", slug: "oziva", category: "Nutrition", query: "Oziva", aliases: ["oziva"] },
  { name: "The Health Factory", slug: "the-health-factory", category: "Bakery", query: "The Health Factory", aliases: ["health factory"] },
  { name: "Go Desi", slug: "go-desi", category: "Snacks", query: "Go Desi Snacks", aliases: ["go desi"] },
  { name: "Nourish You", slug: "nourish-you", category: "Healthy Snacks", query: "Nourish You", aliases: ["nourish you"] },
  { name: "Fit & Flex", slug: "fit-and-flex", category: "Healthy Snacks", query: "Fit & Flex", aliases: ["fit flex"] },
  { name: "Masala Tokri", slug: "masala-tokri", category: "Ingredients", query: "Masala Tokri", aliases: ["masala tokri"] },
  { name: "The Better Flour", slug: "the-better-flour", category: "Staples", query: "The Better Flour", aliases: ["better flour"] },
  { name: "Millet Amma", slug: "millet-amma", category: "Packaged Food", query: "Millet Amma", aliases: ["millet amma"] },
  { name: "Organic Tattva", slug: "organic-tattva", category: "Staples", query: "Organic Tattva", aliases: ["organic tattva"] },
  { name: "24 Mantra Organic", slug: "24-mantra-organic", category: "Staples", query: "24 Mantra Organic", aliases: ["24 mantra"] },
  { name: "Smoor Chocolates", slug: "smoor", category: "Snacks & Sweets", query: "Smoor Chocolates", aliases: ["smoor"] },
  { name: "Mason & Co", slug: "mason-and-co", category: "Snacks & Sweets", query: "Mason & Co Chocolate", aliases: ["mason co"] },
  { name: "Paul and Mike", slug: "paul-and-mike", category: "Snacks & Sweets", query: "Paul and Mike Chocolate", aliases: ["paul mike"] },
  { name: "Manam Chocolate", slug: "manam-chocolate", category: "Snacks & Sweets", query: "Manam Chocolate", aliases: ["manam"] },
  { name: "Araku Coffee", slug: "araku-coffee", category: "Coffee", query: "Araku Coffee", aliases: ["araku"] },
  { name: "Third Wave Coffee", slug: "third-wave-coffee", category: "Coffee", query: "Third Wave Coffee", aliases: ["third wave coffee"] },
  { name: "Beanly Coffee", slug: "beanly-coffee", category: "Coffee", query: "Beanly Coffee", aliases: ["beanly"] },
  { name: "Goodmylk", slug: "goodmylk", category: "Dairy", query: "Goodmylk", aliases: ["goodmylk"] },
  { name: "Alt Co", slug: "alt-co", category: "Dairy", query: "Alt Co India", aliases: ["alt co"] },
  { name: "Grabenord", slug: "grabenord", category: "Dairy", query: "Grabenord", aliases: ["grabenord"] },
  { name: "Let's Try", slug: "lets-try", category: "Snacks", query: "Let's Try Snacks", aliases: ["lets try"] },
];
